### ISSUE TITLE
Thread leak issue with singleton usage

### ISSUE THREAD

**Issue by robmoore** [abashev/vfs-s3#21] opened 2014-05-29 19:27 UTC
We have experienced thread leaks when using the library in what I understand to be a standard way. By that, I mean we are creating a singleton of the manager at start up and continue to use it until the application shuts down at which point we close it. Also, we are closing the files once they've been used. 

To get around the issue we are now closing the file system manager after every usage. This works but seems inefficient and runs counter to the usage as outlined on the Apache VFS site (http://commons.apache.org/proper/commons-vfs/api.html).

**Comment by svella** [comment] 2014-05-29 21:49
What version are you using? I fixed a thread leak in the 2.2.x branch a while back. See #19

**Comment by robmoore** [comment] 2014-05-29 22:30
We are using a snapshot from March 4th of the 2.2.x branch.

**Comment by abashev** [comment] 2014-05-30 04:17
@robmoore do you have any test case or something that I can use for reproducing this? Thread name maybe?

**Comment by svella** [comment] 2014-05-30 13:56
Just thinking about this I can tell what's going on. A FileSystemManager creates a provider object for each registered protocol (or perhaps only when the protocol is first used). Each provider will create a new file system object for each unique combination of root (bucket in the case of S3) and options (at least key and secret for S3) as needed when resolving a file. Each of these file systems is cached for reuse, and in the case of S3 the file system object will create and hold on to a TransferManager that holds on to Thread pool of up to 10 threads (depending on usage). The fix that I added causes all of these to get cleaned up when the manager gets shut down, but it doesn't do anything about the fact that if you use a lot of buckets and a lot of keys, you are going to have a TransferManager hanging around with up to 10 threads for each combination that gets used. I can think of several possible fixes:
1. Create and shut down the TransferManager on each usage.
2. Keep a soft reference to the TransferManager so it can get garbage collected and recreate as needed.
3. Create TransferManager as needed and add a cleanup task or LRU cache to allow idle TransferManagers to get cleaned up.
4. Don't use TransferManager at all. Use regular put on small files and low level multipart upload on large files. See http://docs.aws.amazon.com/AmazonS3/latest/dev/llJavaUploadFile.html
5. Use regular put on small files on small files, and use strategy 1 on large files.

**Comment by svella** [comment] 2014-05-30 14:34
Since I'm already chasing some problems we're seeing with large file uploads, I'm going to take a stab at either 4 or 5 over in [my fork](https://github.com/svella/vfs-s3).

**Comment by robmoore** [comment] 2014-05-30 14:37
@abashev I'll ask the developer who was working on this if he recalls the thread name. Also, I'll attempt to create a test that replicates this behavior.

**Comment by robmoore** [comment] 2014-05-30 15:07
@abashev The thread name was s3-transfer-manager-worker-1

**Comment by robmoore** [comment] 2014-05-30 17:33
@svella In our case we don't have a lot of buckets or keys. We use one or perhaps two buckets and a single key for each. Just wanted to provide some context.

**Comment by svella** [comment] 2014-05-30 17:38
@robmoore - how many extra threads are you seeing? Just a up to 10 per bucket (depending on usage patterns) that never seem to go away or are you seeing the thread count just keep growing until no more threads can be created?

**Comment by robmoore** [comment] 2014-05-30 18:19
It keeps growing until the JVM dies. In one instance it grew to nearly 1200 threads over a week or two.

**Comment by robmoore** [comment] 2014-05-31 00:55
I've created this example: https://github.com/robmoore/vfs-s3-test

I've uploaded up to 50 files and the number of threads stays in step with the number of uploads I've performed. It may be that the test needs to run longer in order for the thread count to shrink.

**Comment by svella** [comment] 2014-05-31 02:58
It looks like the way vfs-s3 S3FileProvider allows you to set default options on the S3FileProvider class is the culprit here. Besides not being safe from the point of reuse, it also isn't compatible with how the caching system finds the FileSystem object for the same bucket with the same set of options because it looks up using null options if you don't pass anything in on the resolve, but caches using the defaults that S3FileProvider ends up using. So what happens is that every time you resolve from scratch you get a new FileSystem object with a new thread pool. I can't really think of a way to fix that problem in a backward compatible way other than to say don't ever resolve from scratch without passing in a set of options, even if they are the default ones.

So instead of:

```
remote = fsManager.resolveFile(remotePath);
```

do:

```
remote = fsManager.resolveFile(remotePath, S3FileProvider.getDefaultFileSystemOptions());
```

or better yet, resolve to the bucket root once, and then use it to resolve everything else, which is more in line with how VFS is typically used anyway.

```
    private FileObject localRoot;

    @PostConstruct
    private void init() throws FileSystemException {
        remoteRoot = fsManager.resolveFile(getBasePath(),
                S3FileProvider.getDefaultFileSystemOptions());
    }
```

and then later:

```
remote = remoteRoot.resolveFile(file.getName());
```

**Comment by robmoore** [comment] 2014-06-01 15:22
@svella Thanks! That did the trick. While this is a workable solution it does occur to me that it isn't obvious to a new comer. In the spirit of "sensible defaults", it seems like the vanilla resolveFile (that is, fsManager.resolveFile(remotePath)) should use the default file system options. If that's not possible, it seems the documentation should make clear the consequences of using the basic resolveFile on the FileSystemManager.

**Comment by ecki** [comment] 2014-12-27 23:07
BTW: in current VFS 2.1 trunk the logic about closing a file system and removing entries from the cache is fixed as there have been some leaks. Maybe you can re-test without closing the manager?

**Closed as completed** 2016-08-23 10:51 UTC
